use attendance_service::{app, schema::app::AppState};
use axum_test::TestServer;
use sqlx::postgres::PgPoolOptions;
use testcontainers_modules::{postgres, testcontainers::runners::AsyncRunner};

//this test wont run, the seed is only applied to the real database, not the test container
#[tokio::test]
async fn log_user() {
    let container = postgres::Postgres::default().start().await.unwrap();
    let host_port = container.get_host_port_ipv4(5432).await.unwrap();
    let url = format!("postgres://postgres:postgres@127.0.0.1:{host_port}/postgres"); //default credentials generated by testcontainer

    let pool = PgPoolOptions::new()
        .connect(url.as_str())
        .await
        .expect("Failed to connect to database");

    let appstate = AppState {
        pool: pool,
        secret: "your_secret_key_here".to_string(),
    };

    let server = TestServer::new(app(appstate));

    let response = server
        .post("/auth")
        .json(&serde_json::json!({
            "email": "john.doe@example.com",
            "password": "JohnPassword123!"
        }))
        .await;

    response.assert_status_ok();
}
