name: attendance-service

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    ALLOWED_ORIGIN: ${{ secrets.ALLOWED_ORIGIN }}
    API_URL: ${{ secrets.API_URL }}
    APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    SMTP_HOST: ${{ secrets.SMTP_HOST }}
    SMTP_NAME: ${{ secrets.SMTP_NAME }}
    SMTP_PORT: ${{ secrets.SMTP_PORT }}
    SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
    SQLX_OFFLINE: ${{ secrets.SQLX_OFFLINE }}
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: rustup toolchain install stable --profile minimal # for cache to work
            - name: Rust chache
              uses: swatinem/rust-cache@v2
            - name: prepare sqlx
              run: cargo install sqlx-cli

            - name: create database
              run: docker compose up -d --wait

            - name: create tables
              run: sqlx migrate run
            - name: compare database queries
              run: cargo sqlx prepare --check

            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
